import assert from "node:assert/strict";
import { loadBookingAvailability } from "../features/test-drive/services/availabilityApi";
import { buildAvailabilityResult, normalizeSlots } from "../features/test-drive/utils/availability";
import { isValidBookingDate } from "../features/test-drive/utils/bookingDate";

const today = new Date(2026, 7, 19);
assert.equal(isValidBookingDate("2026-08-19", today), true);
assert.equal(isValidBookingDate("2026-08-18", today), false);
assert.equal(isValidBookingDate("2026-02-30", today), false);
const slots = normalizeSlots(["09:00", "09:00", "10:00"], ["09:00"]);
assert.deepEqual(slots, [{ time: "09:00", available: true }, { time: "10:00", available: false }]);
const built = buildAvailabilityResult({ vehicleId: "12", date: "2026-08-20", allSlots: ["09:00", "10:00"], availableSlots: ["09:00"], mock: false, message: "ok" });
assert.deepEqual(built.reservedSlots, ["10:00"]);
const invalid = await loadBookingAvailability("", "2026-08-20", { mockMode: true, today });
assert.equal(invalid.success, false);
const mock = await loadBookingAvailability("101", "2026-08-20", { mockMode: true, today });
assert.equal(mock.success, true);
if (!mock.success) throw new Error(mock.message);
assert.deepEqual(mock.reservedSlots, ["10:00", "11:30"]);
assert.equal(mock.mock, true);
const serverFailure = await loadBookingAvailability("101", "2026-08-20", { today, fetcher: async () => new Response("{}", { status: 500 }) });
assert.equal(serverFailure.success, false);
const malformed = await loadBookingAvailability("101", "2026-08-20", { today, fetcher: async () => new Response("{}", { status: 200, headers: { "Content-Type": "application/json" } }) });
assert.equal(malformed.success, false);
const controller = new AbortController(); controller.abort();
const aborted = await loadBookingAvailability("101", "2026-08-20", { mockMode: true, today, signal: controller.signal });
assert.equal(aborted.success, false);
if (!aborted.success) assert.equal(aborted.code, "ABORTED");
console.log(JSON.stringify({ suite: "bookingAvailability", passed: 12, failed: 0, syntheticDataUsed: true, browserSuppliedUserId: false }, null, 2));
